export { About } from "./About"
export { Contact } from "./Contact"
export { Footer } from "./Footer"
export { Header } from "./Header"
export { Hero } from "./Hero"
export { Portfolio } from "./Portfolio"
export { SEO } from "./SEO"
export { Service } from "./Service"
