#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Checking for formatting, lints, typesafety and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier Check Failed: Run npm run format and try committing again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo 'ESLint Check Failed: Make the changes listed above and try to commit again.'
        false;
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Fix all the typescript issues listed above and try to commit again.'
    false;
)

# If everything passes...
echo 'All checks passed attempting to build project'

npm run build ||
(
    echo 'build failed: Check the errors above to see why.'
    false;
)

# If everything passes...
echo 'All checks clear. committing the code now.'